- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/BackButton.jsx
- client/src/components/GymNewest.jsx
- client/src/components/GymNewestList.jsx
- client/src/components/GymTabList.jsx
- client/src/components/HeaderTitle.jsx
- client/src/components/layout/Header.jsx
- client/src/components/layout/Main.jsx
- client/src/components/layout/Nav.jsx
- client/src/pages/GymPage.jsx
- client/tailwind.config.js
> design: 레이아웃 추가

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/ErrorFallback.jsx
- client/src/components/GymNewest.jsx
- client/src/components/GymNewestList.jsx
- client/src/components/Loading.jsx
- client/src/components/UI/ChatButton.jsx
- client/src/components/UI/HeartButton.jsx
- client/src/components/layouts/Header/Header.jsx
- client/src/components/layouts/Main/Main.jsx
- client/tailwind.config.js
> design: GYM페이지 수정

- client/package-lock.json
- client/src/components/UI/Board/BoardPost.jsx
- client/src/components/UI/Board/BoardPostBody.jsx
- client/src/components/UI/Board/BoardPostTitle.jsx
- client/src/components/UI/Board/BoardTabList.jsx
- client/src/components/UI/TabButton.jsx
- client/src/components/UI/TextInput.jsx
- client/src/pages/BoardPostPage.jsx
> design:BoardPostForm 작업

- back/build.gradle
- back/src/main/java/main012/server/HelloController.java
- back/src/test/java/main012/server/ServerApplicationTests.java
> Test: crossOrigin 테스트

- back/.gitignore
- back/src/main/java/main012/server/common/Auditable.java
- back/src/main/java/main012/server/user/entity/User.java
- back/src/main/java/main012/server/user/entity/UserInfo.java
> Init: 초기 설정

- .github/workflows/gradle.yml
- back/src/main/resources/application.yml
> Fix: 초기 설정 수정

- back/src/main/java/main012/server/user/entity/Role.java
- back/src/main/java/main012/server/user/entity/User.java
- back/src/main/java/main012/server/user/entity/UserInfo.java
> Feat: 유저 엔티티 설계

- back/src/main/java/main012/server/user/entity/User.java
Feat: UserStatus 추가, cascade 수정
> Feat: UserStatus 추가, cascade 수정

- back/src/main/java/main012/server/ServerApplication.java
- back/src/main/java/main012/server/community/entity/Community.java
- back/src/main/java/main012/server/community/entity/CommunityBookmark.java
- back/src/main/java/main012/server/community/entity/CommunityComment.java
- back/src/main/java/main012/server/gym/entity/Gym.java
- back/src/main/java/main012/server/gym/entity/GymBookmark.java
- back/src/main/java/main012/server/gym/entity/GymReview.java
- back/src/main/java/main012/server/image/entity/Image.java
- back/src/main/java/main012/server/user/controller/MemberController.java
- back/src/main/java/main012/server/user/dto/MemberDto.java
- back/src/main/java/main012/server/user/entity/Member.java
- back/src/main/java/main012/server/user/mapper/MemberMapper.java
- back/src/main/java/main012/server/user/repository/MemberRepository.java
- back/src/main/java/main012/server/user/service/MemberService.java
- back/src/main/resources/application.yml
> Rename: User -> Member 이름 수정

- client/src/components/Board/BoardSearchContainer.jsx
- client/src/components/Gym/GymHours.jsx
- client/src/components/Gym/GymHoursContainer.jsx
- client/src/components/Gym/GymPriceTableContainer.jsx
- client/src/components/Gym/GymReviewPost.jsx
> design: GYM 페이지 수정진행중

- client/src/components/Gym/GymHours.jsx
- client/src/components/Gym/GymPhoneNumber.jsx
- client/src/components/Gym/GymPhoneNumberContainer.jsx
- client/src/components/Gym/GymPostAddress.jsx
- client/src/components/Gym/GymPostDetailPrice.jsx
- client/src/components/Gym/GymPostFacilitiesTagList.jsx
- client/src/components/Gym/GymPostHours.jsx
- client/src/components/Gym/GymPostImage.jsx
- client/src/components/Gym/GymPostName.jsx
- client/src/components/Gym/GymPostPhoneNumber.jsx
- client/src/components/Gym/GymPostPrice.jsx
- client/src/components/UI/BackButton.jsx
- client/src/components/UI/CompleteButton.jsx
- client/src/components/layouts/Modal/Modal.jsx
- client/src/components/layouts/More.jsx
> design: 목업 수정

- client/src/components/Board/Board.jsx
- client/src/components/Board/BoardList.jsx
- client/src/components/layouts/Header/Header.jsx
- client/src/pages/BoardPage.jsx
> design: Board 레이아웃 수정

- client/src/components/UI/Input/TextInput.jsx
> design: TextInput 수정

- client/src/components/Board/Post/PostBody.jsx
> feat: Board post 페이지 에디터 추가

- back/src/main/java/main012/server/advice/GlobalExceptionAdvice.java
- back/src/main/java/main012/server/exception/ExceptionCode.java
- back/src/main/java/main012/server/user/controller/MemberController.java
- back/src/main/java/main012/server/user/dto/MemberInfoDto.java
- back/src/main/java/main012/server/user/dto/MemberRequestDto.java
- back/src/main/java/main012/server/user/dto/MemberResponseDto.java
- back/src/main/java/main012/server/user/entity/Member.java
- back/src/main/java/main012/server/user/mapper/MemberMapper.java
- back/src/main/java/main012/server/user/service/MemberService.java
- back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Feat: 마이페이지 메인 조회, 비밀번호 수정, 프로필 수정
> Feat: 마이페이지 메인 조회, 비밀번호 수정, 프로필 수정

- back/src/main/java/main012/server/auth/controller/AuthController.java
- back/src/main/java/main012/server/auth/filter/JwtAuthenticationFilter.java
- back/src/main/java/main012/server/auth/jwt/JwtTokenizer.java
- back/src/main/java/main012/server/auth/service/AuthService.java
- back/src/main/java/main012/server/auth/service/MemberDetailsService.java
- back/src/main/java/main012/server/exception/ExceptionCode.java
- back/src/main/java/main012/server/user/controller/MemberController.java
- back/src/main/java/main012/server/user/dto/MemberRequestDto.java
- back/src/main/java/main012/server/user/entity/Member.java
- back/src/main/java/main012/server/user/service/MemberService.java
- back/src/main/java/main012/server/user/service/MemberServiceImpl.java
> Feat: 회원 탈퇴, AccessToken 재발급

- back/src/main/java/main012/server/auth/config/SecurityConfiguration.java
- back/src/main/java/main012/server/auth/controller/AuthController.java
- back/src/main/java/main012/server/community/controller/CommentController.java
- back/src/main/java/main012/server/community/controller/CommunityController.java
- back/src/main/java/main012/server/gym/controller/GymController.java
- back/src/main/java/main012/server/user/controller/MemberController.java
일단 Controller에 @CrossOrigin 붙였습니다
> Fix: CORS 설정

- back/src/main/java/main012/server/community/controller/CommentController.java
- back/src/main/java/main012/server/community/controller/CommunityController.java
- back/src/main/java/main012/server/community/dto/CommentDto.java
- back/src/main/java/main012/server/community/dto/CommunityDto.java
- back/src/main/java/main012/server/community/entity/CommunityBookmark.java
- back/src/main/java/main012/server/community/mapper/CommentMapper.java
- back/src/main/java/main012/server/community/mapper/CommunityMapper.java
- back/src/main/java/main012/server/community/repository/CommunityBookmarkRepository.java
- back/src/main/java/main012/server/community/repository/CommunityRepository.java
- back/src/main/java/main012/server/community/service/CommunityBookmarkService.java
- back/src/main/java/main012/server/community/service/CommunityService.java
> feat : 찜, 탭별 커뮤니티 조회, 검색기능 구현

- back/src/main/java/main012/server/user/dto/MemberInfoDto.java
- back/src/main/java/main012/server/user/mapper/MemberMapper.java
- back/src/main/java/main012/server/user/service/MemberServiceImpl.java
> Fix: 마이페이지 헬스장 찜 조회 수정

- client/package-lock.json
- client/public/index.html
- client/src/App.jsx
- client/src/components/Board/Board.jsx
- client/src/components/Board/Comment/CommentHeader.jsx
- client/src/components/My/Detail/MyDetailList.jsx
- client/src/components/My/Detail/MyDetailListItem.jsx
- client/src/components/My/Detail/MyDetailTitle.jsx
- client/src/components/My/MyPageList.jsx
- client/src/components/My/Password/CheckPasswordList.jsx
- client/src/components/My/Password/PasswordList.jsx
- client/src/components/My/Profile.jsx
- client/src/components/UI/Button/EditButton.jsx
- client/src/components/UI/Button/MyPageButton.jsx
- client/src/components/UI/DisplayName/DisplayName.jsx
- client/src/components/UI/ProfileImg/ProfileImg.jsx
- client/src/components/layouts/Header/Header.jsx
- client/src/index.js
- client/src/mocks/dummyData.jsx
- client/src/mocks/handlers.jsx
- client/src/pages/Home/Home.jsx
- client/src/pages/My/MyDetail.jsx
- client/src/pages/My/MyPage.jsx
- client/src/state/useStore.jsx
> feat: 마이페이지 구현중

- client/src/components/My/Detail/MyDetailList.jsx
- client/src/components/My/MyPageList.jsx
- client/src/pages/Home/Home.jsx
- client/src/pages/My/MyPage.jsx
> feat: 마이페이지 기능구현중

- back/src/main/java/main012/server/advice/GlobalExceptionAdvice.java
- back/src/main/java/main012/server/auth/config/SecurityConfiguration.java
- back/src/main/java/main012/server/auth/filter/JwtVerificationFilter.java
- back/src/main/java/main012/server/auth/handler/MemberAuthenticationEntryPoint.java
- back/src/main/java/main012/server/auth/resolver/MemberArgumentResolver.java
- back/src/main/java/main012/server/community/repository/CommunityBookmarkRepository.java
- back/src/main/java/main012/server/community/repository/CommunityRepository.java
- back/src/main/java/main012/server/exception/ExceptionCode.java
- back/src/main/java/main012/server/gym/controller/GymReviewController.java
- back/src/main/java/main012/server/gym/mapper/GymReviewMapper.java
- back/src/main/java/main012/server/gym/repository/GymBookmarkRepository.java
- back/src/main/java/main012/server/gym/repository/GymRepository.java
- back/src/main/java/main012/server/user/controller/MemberController.java
- back/src/main/java/main012/server/user/dto/MemberInfoDto.java
- back/src/main/java/main012/server/user/dto/MemberResponseDto.java
- back/src/main/java/main012/server/user/mapper/MemberMapper.java
- back/src/main/java/main012/server/user/service/MemberService.java
- back/src/main/java/main012/server/user/service/MemberServiceImpl.java
- Security exception 수정
- member 메인 페이지 조회 로직 수정
- gym review 등록할 때, gym mapping 수정
> Fix: Security, Member, GymReview 수정

- back/src/main/java/main012/server/auth/config/SecurityConfiguration.java
securityConfiguration 에 h2 permitAll 추가
> Chore: h2 permitAll 추가

- client/src/components/My/Detail/MyDetailList.jsx
- client/src/components/My/Profile.jsx
- client/src/components/UI/Button/TabButton.jsx
- client/src/components/UI/ProfileImg/ProfileImg.jsx
> feat: 마이페이지 기능 구현중

- client/src/components/My/Password/PasswordList.jsx
- client/src/components/My/Password/PasswordNow.jsx
- client/src/components/My/Profile.jsx
- client/src/components/UI/Button/BackButton.jsx
- client/src/components/UI/Button/TabButton.jsx
- client/src/components/UI/Form/FormGroup.jsx
- client/src/context/form-group-context.jsx
- client/src/index.js
- client/src/pages/My/MyPage.jsx
- client/src/state/useMyStore.jsx
- client/src/utils/validate.js
> feat: 마이페이지 프로필수정 구현중

- client/src/components/My/Detail/MyDetailList.jsx
- client/src/components/My/Detail/MyDetailListItem.jsx
- client/src/components/My/Password/PasswordList.jsx
- client/src/components/My/Profile.jsx
- client/src/components/UI/DisplayName/DisplayName.jsx
> feat: 마이페이지 프로필 수정기능 구현중

- back/src/main/generated/main012/server/community/mapper/CommentMapperImpl.java
- back/src/main/generated/main012/server/community/mapper/CommunityMapperImpl.java
- back/src/main/generated/main012/server/gym/mapper/GymMapperImpl.java
- back/src/main/generated/main012/server/gym/mapper/GymReviewMapperImpl.java
- back/src/main/generated/main012/server/user/mapper/MemberMapperImpl.java
- back/src/main/java/main012/server/gym/dto/GymDto.java
- back/src/main/java/main012/server/gym/dto/GymReviewDto.java
- back/src/main/java/main012/server/gym/entity/Gym.java
- back/src/main/java/main012/server/gym/entity/GymPrice.java
- back/src/main/java/main012/server/gym/mapper/GymMapper.java
- back/src/main/java/main012/server/gym/mapper/GymReviewMapper.java
- back/src/main/java/main012/server/user/service/MemberServiceImpl.java
Feat: 리뷰 상세조회에서 memerId 와 reviewId 보임
rename: gymPrice삭제
> 리뷰수정, 헬스장 가격 목록 삭제

- client/src/App.jsx
- client/src/components/Login/Login.jsx
- client/src/components/My/Detail/MyDetailTitle.jsx
- client/src/components/My/Profile.jsx
- client/src/components/UI/Button/LogoutButton.jsx
- client/src/components/UI/Button/MyPageButton.jsx
- client/src/components/layouts/Header/Header.jsx
- client/src/pages/Home/Home.jsx
- client/src/pages/My/MyPage.jsx
- client/src/state/useStore.jsx
> feat: 로그인연결 외 수정

- client/src/components/Board/Board.jsx
- client/src/components/Board/BoardContentList.jsx
- client/src/components/Board/Comment/CommentBody.jsx
- client/src/components/Board/Comment/CommentList.jsx
- client/src/components/Board/Comment/CommentPost.jsx
- client/src/components/Board/Container/Header.jsx
- client/src/components/Board/Detail/BoardDetail.jsx
- client/src/components/Board/Detail/DetailBody.jsx
- client/src/components/Board/Detail/DetailComment.jsx
- client/src/components/Board/Detail/DetailHeader.jsx
- client/src/components/Board/Detail/DetailTab.jsx
- client/src/components/Board/Detail/DetailTitle.jsx
- client/src/components/Board/Post/BoardPost.jsx
- client/src/components/UI/Button/HeartButton.jsx
- client/src/components/UI/HeartContainer.jsx
- client/src/pages/My/MyPage.jsx
- client/src/utils/dateFormat.js
feat: 커뮤니티 전체조회, 상세조회 일부 기능 수정
> feat: 커뮤니티 전체조회, 상세조회 일부 기능 수정

- back/src/main/java/main012/server/gym/controller/GymController.java
- back/src/main/java/main012/server/gym/dto/GymWithDistance.java
- back/src/main/java/main012/server/gym/entity/Gym.java
- back/src/main/java/main012/server/gym/mapper/GymMapper.java
- back/src/main/java/main012/server/gym/service/GymService.java
filter : grade(평점순), bookmark(찜순), distance(거리순, default)
> Feat: 헬스장 목록 필터링

- client/src/components/My/Detail/MyDetailListItem.jsx
- client/src/components/My/MyAccount.jsx
- client/src/components/My/MyPageList.jsx
- client/src/components/My/Profile.jsx
- client/src/components/layouts/Modal/Modal.jsx
- client/src/pages/My/MyPage.jsx
> feat: 마이페이지 프로필 수정 기능 구현중

- client/src/components/Login/Login.jsx
- client/src/components/My/Detail/MyDetailListItem.jsx
- client/src/components/My/Detail/MyDetailTitle.jsx
- client/src/components/My/Password/CheckPasswordList.jsx
- client/src/components/My/Password/PasswordNewCheck.jsx
- client/src/components/layouts/Modal/Modal.jsx
- client/src/utils/api.jsx
> feat: 회원탈퇴 기능 구현

- client/src/components/My/Password/PasswordList.jsx
- client/src/components/My/Profile.jsx
> feat: 비밀번호 수정 기능구현

- back/src/main/java/main012/server/gym/controller/GymController.java
- back/src/main/java/main012/server/gym/dto/GymDto.java
- back/src/main/java/main012/server/gym/mapper/GymMapper.java
- back/src/main/java/main012/server/gym/service/GymService.java
- back/src/main/java/main012/server/user/controller/MemberController.java
- back/src/main/java/main012/server/user/service/MemberServiceImpl.java
이미지 안들어와도 헬스장 등록, 수정/ 프로필 수정할 수 있게 변경
> Fix: 이미지 RequestPart require false

- client/src/components/My/Detail/MyDetailList.jsx
- client/src/components/My/Detail/MyDetailListItem.jsx
> fix: 마이페이지 헬스장찜목록 수정

- client/src/components/Login/Login.jsx
- client/src/components/My/MyAccount.jsx
- client/src/components/My/Profile.jsx
- client/src/components/SignUp/SignUp.jsx
> fix: 마이페이지 프로필수정 기능 수정

- client/src/components/Board/Comment/CommentBody.jsx
- client/src/components/Board/Comment/CommentPost.jsx
- client/src/components/Board/Detail/BoardDetail.jsx
> fix: 커뮤니티 댓글 조회 수정

- client/src/components/My/Detail/MyDetailList.jsx
- client/src/components/My/Detail/MyDetailListItem.jsx
- client/src/components/My/MyPageList.jsx
- client/src/components/UI/Button/MyPageButton.jsx
- client/src/components/layouts/Header/Header.jsx
> fix: 마이페이지 목록조회 수정

- client/src/components/My/Detail/MyDetailList.jsx
- client/src/components/My/Detail/MyDetailListItem.jsx
> fix: 마이페이지 헬스장 찜목록 이미지 수정

- client/src/components/Board/BoardContentList.jsx
- client/src/components/Board/Container/Search.jsx
- client/src/components/Gym/Review/Review.jsx
- client/src/components/My/Password/PasswordList.jsx
- client/src/components/My/Profile.jsx
- client/src/components/UI/Button/LogoutButton.jsx
- client/src/components/UI/More.jsx
- client/src/components/UI/ProfileImg/ProfileImg.jsx
- client/src/pages/Board/Board.jsx
- client/src/pages/Gym/GymPost.jsx
- client/src/pages/SignUp/OwnerSignUpPage.jsx
> feat: 커뮤니티 페이지 키워드 검색 기능 구현

- client/src/components/Board/Board.jsx
- client/src/components/Board/BoardContentList.jsx
- client/src/components/UI/Button/HeartButton.jsx
> feat: 커뮤니티 페이지 찜 기능 구현중

- client/src/App.jsx
- client/src/components/layouts/Main/Main.jsx
- client/src/theme.css
> design: 레이아웃 수정
